import fs from 'node:fs/promises';
import path from 'node:path';
import { collections } from '../src/collections.mjs';

const root = path.resolve(import.meta.dirname, '..');
const assets = JSON.parse(await fs.readFile(path.join(root,'src/assets.json'),'utf8'));
const products = JSON.parse(await fs.readFile(path.join(root,'src/products.json'),'utf8'));
const esc = value => String(value).replaceAll('&','&amp;').replaceAll('"','&quot;').replaceAll('<','&lt;').replaceAll('>','&gt;');
const arrow = '<svg class="arrow" viewBox="0 0 44 28" fill="none" aria-hidden="true"><path d="M1 14h39M29 2l12 12-12 12" stroke="currentColor" stroke-width="1.3"/></svg>';
const line = '<svg class="draw-line" viewBox="0 0 300 3" preserveAspectRatio="none" aria-hidden="true"><path d="M0 1.5H300" fill="none" stroke="currentColor" stroke-width="1" pathLength="1"/></svg>';
const price = p => `¥${p.toLocaleString('ja-JP')}`;
const href = (prefix,slug) => `${prefix}collections/${slug}/`;
const lookbookNote = '※掲載している着用イメージは、商品画像をもとに制作したイメージビジュアルです。実際の商品を着用して撮影したものではないため、色味・質感・サイズ感などが実物と異なる場合があります。';
const image = (src,prefix,alt,extra='') => `<img src="${prefix}${src}" srcset="${prefix}${src.replace('.webp','-640.webp')} 640w, ${prefix}${src} 1400w" sizes="(max-width: 600px) 50vw, 60vw" alt="${esc(alt)}" decoding="async" ${extra}>`;
function renderLookbook(files,prefix,c){
  return `<section class="lookbook-section" aria-labelledby="lookbook-title"><div class="lookbook-heading"><span class="index">03</span><div><h2 id="lookbook-title">LOOK BOOK</h2></div><span class="micro">05 VISUALS / 横スクロール</span></div><div class="lookbook-track" tabindex="0" role="group" aria-label="${esc(c.name)}の着用イメージ（横スクロール）">${files.map((src,i)=>`<button class="lookbook-item" type="button" data-lightbox="${prefix}${src}" data-caption="${esc(c.short)} LOOK BOOK ${String(i+1).padStart(2,'0')}" data-cursor="VIEW" aria-label="着用イメージ${i+1}を拡大表示"><picture><source media="(max-width:600px)" srcset="${prefix}${src.replace('.webp','-640.webp')}"><img src="${prefix}${src}" alt="${esc(c.name)} 着用イメージ ${i+1}" width="941" height="1672" loading="lazy" decoding="async"></picture></button>`).join('')}</div><p class="lookbook-note">${lookbookNote}</p></section>`;
}
function slides(files,prefix,alt,priority=false){
  return `<div class="slideshow" data-slides="${esc(JSON.stringify(files.map(f=>prefix+f)))}">${image(files[0],prefix,alt,`class="slide is-active" ${priority?'fetchpriority="high"':'loading="lazy"'}`)}<img class="slide slide-next" alt="" aria-hidden="true" decoding="async"></div>`;
}
function menu(prefix,current=''){
  return `<button class="menu-toggle" aria-label="コレクションメニューを開く" aria-expanded="false" aria-controls="collection-menu"><span></span><span></span><span class="menu-label">MENU</span></button>
  <dialog class="nav-dialog" id="collection-menu" aria-label="コレクションメニュー"><div class="nav-top"><a class="wordmark" href="${prefix}">URBAN RIDER TOKYO</a><button class="menu-close" aria-label="メニューを閉じる">CLOSE <span>×</span></button></div><div class="nav-layout"><div class="nav-intro"><span class="eyebrow">FIND YOUR OWN WAY.</span><p>好きな絵で、<br>生きていく。</p><a href="${prefix}" class="text-link">すべてのコレクション ${arrow}</a></div><nav aria-label="コレクション一覧">${collections.map(c=>`<a href="${href(prefix,c.slug)}" ${current===c.slug?'aria-current="page"':''}><span class="index">${c.number}</span><span class="nav-name">${c.slug==='animal'?'ANIMAL DESIGN':c.short}</span><span class="nav-collection">COLLECTION</span>${arrow}</a>`).join('')}</nav></div><div class="nav-bottom eyebrow">GRAPHIC T-SHIRT SHOP <span>TOKYO, JAPAN</span></div></dialog>`;
}
function footer(prefix){
  return `<footer class="site-footer"><div><a href="${prefix}" class="wordmark">URBAN RIDER TOKYO</a><p class="eyebrow footer-sub">TOKYO STREET CULTURE WEAR</p><span class="dash"></span><p>好きなものと、どこまでも。</p><span class="micro">CLOTHES FOR A FREER TOMORROW.</span></div><nav aria-label="フッターナビゲーション"><a href="${prefix}#collections">COLLECTIONS</a><a href="${prefix}#about">ABOUT URT</a><a href="https://suzuri.jp/URBAN_RIDER_TOKYO" target="_blank" rel="noopener noreferrer">ONLINE STORE ↗</a></nav><div class="footer-note"><span class="eyebrow">WEAR.<br>RIDE.<br>BE YOURSELF.</span><span class="dash"></span><p>東京から、自由な毎日へ。</p></div><div class="copyright micro"><span>© ${new Date().getFullYear()} URBAN RIDER TOKYO</span><a href="#top">BACK TO TOP ↑</a></div></footer>`;
}
function shell(content,{prefix='',collection=null}={}){
  const title=collection?`${collection.name} | URBAN RIDER TOKYO`:'URBAN RIDER TOKYO | 都市を駆ける、自由な魂へ。';
  const description=collection?collection.concept:'都市を駆ける、自由な魂へ。東京のバイク＆ストリートカルチャーを、毎日のグラフィックTシャツに。6つのコレクションから、自分らしい一枚を。';
  return `<!doctype html><html lang="ja"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1"><meta name="theme-color" content="#ffffff"><meta name="description" content="${esc(description)}"><meta property="og:title" content="${esc(title)}"><meta property="og:description" content="${esc(description)}"><meta property="og:type" content="website"><title>${esc(title)}</title><link rel="icon" href="${prefix}favicon.svg" type="image/svg+xml"><script>(function(){try{var w=JSON.parse(sessionStorage.getItem('urt:wipe')||'null');sessionStorage.removeItem('urt:wipe');if(!w||Date.now()-w.t>2500)return;if(matchMedia('(prefers-reduced-motion: reduce)').matches)return;var r=document.documentElement;r.style.setProperty('--wx',w.x+'px');r.style.setProperty('--wy',w.y+'px');r.classList.add('wipe-enter');}catch(e){}})();</script><link rel="preload" href="${prefix}fonts/Anton-Regular.ttf" as="font" type="font/ttf" crossorigin><link rel="preload" href="${prefix}fonts/BebasNeue-Regular.ttf" as="font" type="font/ttf" crossorigin><link rel="stylesheet" href="${prefix}styles.css"><script type="module" src="${prefix}app.js"></script></head><body class="${collection?'brand-page brand-'+collection.slug:'home-page'}" id="top"><a href="#main" class="skip-link">本文へスキップ</a>${content}<dialog class="lightbox" aria-label="画像の拡大表示"><button class="lightbox-close" aria-label="拡大表示を閉じる">CLOSE ×</button><div class="lightbox-content"><img class="lightbox-image" alt=""><div class="lightbox-caption"><p></p><a class="buy-button" target="_blank" rel="noopener noreferrer">購入する ↗</a></div></div></dialog><div class="custom-cursor" aria-hidden="true"><span></span></div><div class="fx-layer" aria-hidden="true"></div></body></html>`;
}
function topCard(slug,style){
  const c=collections.find(c=>c.slug===slug);
  return `<a class="collection-card ${style}" href="${href('',slug)}" data-nav-reveal data-cursor="EXPLORE"><div class="collection-art"><span class="index">${c.number}</span>${slides(assets[slug].top,'',c.name+' グラフィック',style==='primary-card')}<span class="image-note">VIEW COLLECTION ↗</span></div><div class="collection-caption"><h2>${c.name}</h2>${arrow}</div>${line}<p class="collection-tagline">${c.tagline}</p></a>`;
}
function home(){
  return shell(`<div class="home-shell"><aside class="brand-rail" aria-label="URBAN RIDER TOKYO"><div class="rail-top"><p class="eyebrow">TOKYO<br>STREET<br>CULTURE<br>WEAR</p><h1><span>URBAN</span><span>RIDER</span><span>TOKYO</span></h1><span class="trademark">TM</span></div><div class="rail-middle"><p class="eyebrow">ART<br>BIKE<br>ANIMALS<br>AND<br>MORE.</p><div class="rail-copy"><p>好きな絵で、<br>生きていく。</p><span class="eyebrow">GRAPHIC<br>T-SHIRTS<br>FOR A FREER<br>TOMORROW.</span></div></div><div class="rail-bottom"><span class="eyebrow">TOKYO<br>JAPAN</span><span class="dash"></span><p>都市を駆ける<br>自由な魂へ。</p></div></aside><div class="home-main"><header class="home-header"><a href="./" class="shop-title">GRAPHIC T-SHIRT SHOP</a><p>都市を駆ける、自由な魂へ。</p>${menu('')}</header><main id="main"><section id="collections" class="collection-index" aria-label="6つのコレクション"><div class="primary-grid">${topCard('bike','primary-card')}${topCard('gakusei','primary-card offset-card')}</div><div class="secondary-grid">${['animal','army','dokuro'].map(c=>topCard(c,'secondary-card')).join('')}</div><a class="brand-band" href="collections/brand/" data-nav-reveal data-cursor="EXPLORE"><span class="index">06</span><div class="brand-band-type"><span>URBAN RIDER</span><span>TOKYO<span class="small-tm">™</span></span></div><div class="brand-band-info"><div><h2>BRAND COLLECTION</h2>${arrow}</div>${line}<p>好きなものと、どこまでも。</p><div class="micro">THE ORIGINALS.<br>URBAN RIDER TOKYO.</div></div></a><div class="index-meta"><span class="micro">SIX COLLECTIONS. YOUR OWN STYLE.</span><button class="motion-toggle" aria-pressed="false">画像の切替を一時停止 <span>Ⅱ</span></button></div></section><section class="about-urt" id="about"><span class="eyebrow"><span class="index">URT</span> ABOUT THE BRAND</span><h2>着る。走る。<br>自分らしく、生きる。</h2><div><p>東京という街のエネルギーと、自由を愛するライダーのスピリット。<br>バイクに乗る日も、街を歩く日も。<br>好きな一枚から、いつもと少し違う一日へ。</p><span class="micro">GRAPHIC T-SHIRTS & EVERYDAY WEAR</span></div></section></main>${footer('')}</div></div>`);
}
function productName(p,c){
  if(/^\d+$/.test(p.number)) return `${c.short} TEE ${p.number}`;
  return p.number.replace('dokuro_','DOKURO ').replaceAll('_',' / ');
}
function productCard(p,c,prefix,i){
  const name=productName(p,c);
  return `<article class="product-card ${i<2?'featured-product':''}" data-product-id="${p.id}" data-product-index="${i}"><button class="product-image torn-reveal" data-lightbox="${prefix}${p.image}" data-caption="${esc(name)} — ${price(p.price)}（税込）" data-url="${esc(p.url)}" data-cursor="ZOOM" aria-label="${esc(name)}の画像を拡大">${image(p.image,prefix,name,'loading="lazy"')}<span class="zoom-mark" aria-hidden="true">＋</span></button><div class="product-info"><h3>${esc(name)}</h3><span class="dash"></span><p class="product-price">${price(p.price)} <small>税込</small></p><a class="buy-button" href="${esc(p.url)}" target="_blank" rel="noopener noreferrer" aria-label="${esc(name)}を購入する（SUZURI・新しいタブ）">購入する <span>↗</span></a></div></article>`;
}
function brand(c){
  const prefix='../../'; const a=assets[c.slug];
  let ps=products.filter(p=>p.brand===c.slug);
  if(c.slug==='brand') ps=[...ps.filter(p=>p.name.includes('_Tシャツ')),...ps.filter(p=>!p.name.includes('_Tシャツ'))];
  const isBrand=c.slug==='brand';
  const hero=isBrand?[...a.hero].reverse():a.hero;
  const gallery=a.gallery||[];
  const heroArt=isBrand?`<div class="identity-hero">${slides(hero,prefix,'URBAN RIDER TOKYO ロゴ',true)}<span class="identity-tag micro">EST. IN TOKYO / MADE FOR EVERYDAY</span><span class="identity-stamp">URT™</span></div>`:slides(hero,prefix,c.name+' キービジュアル',true);
  const gallerySection=gallery.length?`<section class="editorial-gallery" id="gallery" aria-label="${esc(c.short)} アートギャラリー"><div class="gallery-head"><span class="eyebrow">GALLERY</span><span class="micro">${gallery.length} 点 — 横スクロール ↔</span></div><div class="gallery-scroll" tabindex="0" role="group" aria-label="アート画像（左右スクロール）">${gallery.map((src,i)=>`<figure class="gallery-figure"><button class="gallery-image" data-lightbox="${prefix}${src}" data-caption="${esc(c.short)} GALLERY ${String(i+1).padStart(2,'0')} / ${String(gallery.length).padStart(2,'0')}" data-cursor="VIEW" aria-label="${esc(c.short)}のアート画像 ${i+1} を拡大表示">${image(src,prefix,c.short+' アート '+(i+1),'loading="lazy"')}<span class="zoom-mark" aria-hidden="true">＋</span></button></figure>`).join('')}</div></section>`:'';
  return shell(`<div class="brand-wrap"><header class="brand-header"><a href="${prefix}" class="brand-logo"><span class="wordmark">URBAN RIDER TOKYO</span><span class="micro">TOKYO STREET CULTURE WEAR</span></a><nav class="header-links" aria-label="ページ内ナビゲーション"><a href="#concept">CONCEPT</a>${gallery.length?'<a href="#gallery">GALLERY</a>':''}<a href="#products">SHOP <span>(${ps.length})</span></a></nav>${menu(prefix,c.slug)}</header><main id="main"><section class="brand-hero" aria-label="${esc(c.name)}"><div class="hero-copy"><h1>${c.title.map(t=>`<span>${t}</span>`).join('')}</h1><p class="hero-brand-name">${c.name}</p><span class="dash"></span><p class="micro hero-english">${c.english}<br>SAME GOOD ROADS.</p></div><div class="hero-visual ${isBrand?'identity-visual':''}">${heroArt}<div class="hero-image-meta"><span class="micro">${c.short} / COLLECTION ${c.number}</span><button class="motion-toggle" aria-label="画像の切替を一時停止" aria-pressed="false">Ⅱ</button><span class="slide-count micro">01 / ${String(hero.length).padStart(2,'0')}</span></div></div></section><section class="concept" id="concept"><span class="index">01</span><div><span class="eyebrow">CONCEPT</span><h2>${c.heading}</h2><p>${c.concept}</p><span class="dash"></span><span class="micro">${c.english}</span></div><span class="concept-side micro">SAME<br>YESTERDAY.<br>DIFFERENT<br>TOMORROW.</span></section>${gallerySection}<section class="product-section" id="products"><div class="section-heading"><span class="index">02</span><h2 class="eyebrow">PRODUCTS</h2><span class="micro">${String(ps.length).padStart(2,'0')} ITEMS</span></div><div class="product-grid">${ps.map((p,i)=>productCard(p,c,prefix,i)).join('')}</div>${ps.length>6?`<div class="load-more-wrap"><p class="product-progress micro" aria-live="polite">${ps.length} ITEMS</p><button class="load-more buy-button" hidden>もっと見る <span>＋</span></button></div>`:''}<p class="shop-note">購入・サイズ選択は SUZURI の商品ページで。表示価格は税込です。</p></section><section class="next-collection"><span class="eyebrow">KEEP EXPLORING</span><a href="${href(prefix,collections[(collections.indexOf(c)+1)%6].slug)}"><span class="next-name">${collections[(collections.indexOf(c)+1)%6].name}</span>${arrow}</a><a class="text-link" href="${prefix}#collections">すべてのコレクションを見る</a></section></main>${footer(prefix)}</div>`,{prefix,collection:c});
}
await fs.mkdir(path.join(root,'dist'),{recursive:true});
await fs.cp(path.join(root,'public'),path.join(root,'dist'),{recursive:true});
await fs.writeFile(path.join(root,'dist/index.html'),home());
for(const c of collections){
  const folder=path.join(root,'dist/collections',c.slug);
  await fs.mkdir(folder,{recursive:true});
  const html=brand(c).replace('<section class="next-collection">',`${renderLookbook(assets.lookbook[c.slug],'../../',c)}<section class="next-collection">`);
  await fs.writeFile(path.join(folder,'index.html'),html);
}
await fs.writeFile(path.join(root,'dist/404.html'),'<!doctype html><html lang="ja"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>ページが見つかりません | URBAN RIDER TOKYO</title><body style="font-family:sans-serif;padding:10vw;color:#071e39"><h1>PAGE NOT FOUND</h1><p>お探しのページは見つかりませんでした。</p><a href="javascript:history.back()">前のページへ戻る</a></body></html>');
console.log(`Built 7 pages / ${products.length} products. Output: dist/`);
